export const AUTHENTICATED = "AUTHENTICATED";
export const LOAD_USER = "LOAD_USER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_USER = "SET_USER";
export const UNAUTHENTICATED = "UNAUTHENTICATED";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";